version: '3'

services:
  # api:
  #   build:
  #     dockerfile: ./.docker/local/Dockerfile
  #     context: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - postgres
  #   environment:
  #     - PORT=3000
  #   env_file:
  #     - .env
  #   ports:
  #     - '${PORT:-3000}:3000'

  postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: postgres_bookingtable
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}"]
      retries: 3
      timeout: 5s
volumes:
  postgres:
    driver: local
