export const environment = {
  production: true,
  appUrl: 'http://blog.local',
  appKey: 'secret',
  jwtTtl: '3600000000',
  appEnv: 'local',
  dbLog: true,
  migrationsRun: true,
  dbConnection: 'mysql',
  dbHost: 'localhost',
  dbPort: '3306',
  dbName: 'nest',
  dbUser: 'root',
  dbPass: 'password',
}
